### ISSUE TITLE
Search no working properly

### ISSUE THREAD

**Issue by Repflez** [justync7/DTK#1]
Leaving this to avoid more bug reports about it.

Search currently only returns the first title name it finds. Optimally it should return all results or so, and search title id first, then title name.

**Comment by Lustyn** [comment]
Attempted fix in be9a76b3bd18a9c2dab57569bc94ab543a98a149, still open for suggestions

**Comment by Repflez** [comment]
Current search since 2.0 works better than requested in this issue. It search all fields so this issue doesn't need to be open anymore.
