### ISSUE TITLE
Sorting by region

### ISSUE THREAD

**Issue by Xenosaiga** [justync7/DTK#3]
Due to there being a site that has everything dumped to it and being able to grab an Enctitlekey.bin file I would like to request a way to sort by region by clicking on region.

**Comment by Lustyn** [comment]
I'll work on it. Its tough doing stuff like this due to C# just sucking in general but it's doable.

**Comment by Lustyn** [comment]
Possible with fixed search bar in be9a76b3bd18a9c2dab57569bc94ab543a98a149
